name: Ubuntu 18.04 Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  make-master:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
      - run: sudo apt install libpthread-stubs0-dev -y
      - name: Build
        run: |
          mkdir lua-5.4.2
          tar -xzf 3rdparty/lua-5.4.2.tar.gz -C lua-5.4.2/
          make install -C lua-5.4.2
          mkdir build
          cd build
          cmake ..
          make
