name: ubuntu-16.04

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  make-master:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@master
      - run: sudo apt install libpthread-stubs0-dev -y
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
